### ISSUE TITLE
I wish to read the source code.

### ISSUE THREAD

**Issue by iiome** [xtrp/jupiter#1]
Hi Gabriel,

Congratulations on your [blog post](https://xtrp.io/blog/2020/09/12/using-the-monte-carlo-tree-search-algorithm-in-an-ai-to-beat-2048-and-other-games/). I started looking at the code and everything is minimized.

Any chance I could find the readable source code of the game?

Kind regards,
Guillaume

**Comment by gaberomualdo** [comment]
Hi Guillaume,

The source code for the assets (styles and scripts) of the site are included in the `assets` directory. The game and AI, and AI worker code can be found at `assets/js`. I hope this helps.

— Gabriel
