### ISSUE TITLE
How to implement Monte Carlo algorithms in JavaScript and other languages

### ISSUE THREAD

**Issue by Andrew5c** [xtrp/jupiter#2]
Hi, Gabriel.
Thanks for your amazing work, very interesting! 
I also want to implement this project locally with C++. In your [post](https://xtrp.io/blog/2020/09/12/using-the-monte-carlo-tree-search-algorithm-in-an-ai-to-beat-2048-and-other-games/), you maybe forgot to write the subtitle **How to implement Monte Carlo algorithms in JavaScript and other languages**?
Can you give a more detail about **how to realize it with C++ locally.**?
Thanks very much.

**Comment by gaberomualdo** [comment]
Hi,

The post described the algorithm in detail and gave an example implementation in JavaScript. Writing the code for the algorithm in C++ should be as simple as translating the JavaScript code to C++, implementing or getting a 2048 game class, and going forward from there. There would likely be several features of JavaScript that aren't in C++ like web workers and HTML & CSS for the GUI, but there could be alternative ways to do multithreading and creating a 2048 game GUI in C++. Good luck, and I hope this helps.

— Gabriel

**Comment by Andrew5c** [comment]
> Hi,
> 
> The post described the algorithm in detail and gave an example implementation in JavaScript. Writing the code for the algorithm in C++ should be as simple as translating the JavaScript code to C++, implementing or getting a 2048 game class, and going forward from there. There would likely be several features of JavaScript that aren't in C++ like web workers and HTML & CSS for the GUI, but there could be alternative ways to do multithreading and creating a 2048 game GUI in C++. Good luck, and I hope this helps.
> 
> — Gabriel

OK, I will give a try.
Thank you very much!
